### ISSUE TITLE
UX: allow to use the shell process substitution to provide the identity file when decrypting

### ISSUE THREAD

**Issue by ybycode** [str4d/rage#449] opened 2024-01-17 11:26 UTC
## What were you trying to do

Use bash's process substitution to provide the identity when decrypting a rage encrypted file. I'd find that useful to store identities with [pass](https://www.passwordstore.org/).

This works fine with `age`.

## What happened

Rage errors, "Missing identities":

```
$ rage -d -i <(pass some_age_identity) some_file.age
Error: Missing identities.
Did you forget to specify -i/--identity?


[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report 
```

Thanks!

**Comment by str4d** [comment] 2024-01-17 11:37
Duplicate of #379.

**Closed** 2024-01-17 11:37 UTC
