### ISSUE TITLE
OT: Packaging rage, name conflict

### ISSUE THREAD

**Issue by Firstyear** [str4d/rage#273] opened 2021-11-17 22:14 UTC
Hi there,

I'm currently in the process to submit rage to OpenSUSE, but there is already an existing tool called "rage" in the enlightenment desktop package which is a name conflict. I'm thinking of alternate names that could be provided, and thought you may have some ideas. 

Currently I'm consider r-age or rage-encryption. r-age as it kind of indicates rust-age, but it's also a little confusing for anyone who searches "rage". rage-encryption I think makes more sense since the standard is "age-encyrption" and it should show up in a search for rage as well.

Did you have any thoughts here? Perhaps alternate names for rage in case of conflict in packaging could be listed in the readme to help create a bit more of a unified ecosystem.

Thanks!

**Comment by str4d** [comment] 2021-11-18 12:23
Thanks for looking into packaging `rage`!

This issue is a duplicate of #210; please look there for existing discussion on addressing naming collisions. If there are OpenSUSE-specific considerations, we could continue discussion of those here.

**Comment by str4d** [comment] 2021-11-18 12:28
In fact, it looks like the discussion in #210 was precisely about OpenSUSE, so I'm closing this issue as duplicate. Please continue discussion in the other issue 🙂

**Closed by str4d** 2021-11-18 12:28 UTC
